// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrwOsrVG3LslhCOMfJdMSfJRnq4tGJBiY',
    appId: '1:357360031162:web:5ac87ac184e7a532fbb983',
    messagingSenderId: '357360031162',
    projectId: 'grow-with-me-da691',
    authDomain: 'grow-with-me-da691.firebaseapp.com',
    storageBucket: 'grow-with-me-da691.firebasestorage.app',
    measurementId: 'G-0RC6WS2466',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEEf_GmqvZnQjXoVDvaFz8Ynv9_n_U02w',
    appId: '1:357360031162:android:81cac218e292aea3fbb983',
    messagingSenderId: '357360031162',
    projectId: 'grow-with-me-da691',
    storageBucket: 'grow-with-me-da691.firebasestorage.app',
  );
}
